# Generated by Django 4.0.5 on 2022-06-23 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryDate', models.DateTimeField(auto_now_add=True)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('keyword', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_name', models.CharField(max_length=200)),
                ('trans_date', models.DateField()),
                ('trans_comment', models.CharField(max_length=500)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.query')),
            ],
        ),
    ]
